language: cpp

compiler: gcc

before_install:
 - sudo add-apt-repository -y ppa:beineri/opt-qt-5.10.1-trusty
 - sudo apt-get update -qq
 - sudo apt-get remove sqlite3 libsqlite3-0
 - sudo apt-get purge sqlite3 libsqlite3-0
 - sudo apt-get install -qq qt510base qt510imageformats qt510script qt510svg qt510tools
 - mkdir deps
 - cd deps
 - wget http://sqlitestudio.pl/files/depends/sqlite-2.8.17.tar.gz
 - tar xzf sqlite-2.8.17.tar.gz
 - cd sqlite-2.8.17
 - ./configure
 - make
 - sudo make install
 - sqlite -version || true
 - cd ..
 - wget http://sqlite.org/2018/sqlite-autoconf-3230100.tar.gz
 - tar xzf sqlite-autoconf-3230100.tar.gz
 - cd sqlite-autoconf-3230100
 - ./configure --enable-fts5 --enable-json1 --enable-session
 - make
 - sudo make install
 - sqlite3 --version
 - cd ..
 - sudo apt-get install -qq libtcl8.6 tcl8.6-dev

before_script:
  - mkdir -p ../output/build/Plugins
  - . /opt/qt510/bin/qt510-env.sh
  - qmake --version
  
script:
  - cd ../output/build
  - test $TRAVIS_BRANCH = "master" && qmake DEFINES+=tests CONFIG+=debug ../../SQLiteStudio3 || true
  - test $TRAVIS_BRANCH != "master" && qmake CONFIG+=portable ../../SQLiteStudio3 || true
  - make -j 2
  - cd Plugins
  - test $TRAVIS_BRANCH = "master" && qmake CONFIG+=debug ../../../Plugins || true
  - test $TRAVIS_BRANCH != "master" && qmake CONFIG+=portable ../../../Plugins || true
  - make -j 2
  - test $TRAVIS_BRANCH = "master" && cd ../../SQLiteStudio || true
  - test $TRAVIS_BRANCH = "master" && ls -l || true
  - test $TRAVIS_BRANCH = "master" && export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH" || true
  - test $TRAVIS_BRANCH = "master" && for f in tst_*; do ./$f || break 0; done || true

